name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Change to match your SDK version

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Blazor WebAssembly app
      run: dotnet publish -c Release -o dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/wwwroot
        publish_branch: gh-pages
        force_orphan: true
