name: Copy Files to Root

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Copy HTML files from Views to root
      run: |
        echo "=== Copying HTML files from Views to root ==="
        
        # Copy thanks.html from Views/Home to root folder
        if [ -f "Views/Home/thanks.html" ]; then
          echo "✓ Copying Views/Home/thanks.html to root folder"
          cp "Views/Home/thanks.html" "./thanks.html"
          echo "✓ thanks.html copied successfully"
        else
          echo "⚠ Views/Home/thanks.html not found"
        fi
        
        # Copy index.cshtml if it exists in Views (currently only Index.cshtml exists)
        if [ -f "Views/Home/index.html" ]; then
          echo "✓ Copying Views/Home/index.html to root folder"
          cp "Views/Home/index.html" "./index.html"
          echo "✓ index.html copied successfully"
        else
          echo "⚠ Views/Home/index.html not found, keeping existing index.html in root"
        fi
    
    - name: Copy CSS folder from wwwroot to root
      run: |
        echo "=== Copying CSS folder from wwwroot to root ==="
        
        # Copy wwwroot/css folder to root folder
        if [ -d "wwwroot/css" ]; then
          echo "✓ Copying wwwroot/css folder to root folder"
          cp -r "wwwroot/css" "./css"
          echo "✓ CSS folder copied successfully"
          echo "CSS files copied to ./css/:"
          ls -la ./css/
        else
          echo "⚠ wwwroot/css folder not found"
        fi
    
    - name: Verify copied files
      run: |
        echo "=== Verification of copied files ==="
        echo "HTML files in root:"
        ls -la | grep -E "(index\.html|thanks\.html)" || echo "No HTML files found"
        echo "CSS folder in root:"
        ls -la css/ 2>/dev/null || echo "No CSS folder found"
    
    - name: Commit and push changes (if any)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are any changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          echo "✓ Changes detected, committing files"
          git add thanks.html index.html css/ 2>/dev/null || true
          git commit -m "Auto-copy files from Views and wwwroot/css to root folder [skip ci]"
          git push
          echo "✓ Changes committed and pushed"
        else
          echo "ℹ No changes to commit"
        fi
